api/urls.py
from django.conf.urls import url
from rest_framework.authtoken import views

from api.views import LocationListView, UserListView


urlpatterns = [
    url(r'^token-auth', views.obtain_auth_token),

    url(r'^locations/$', LocationListView.as_view()),
    url(r'^users/$', UserListView.as_view()),
]

motley/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('web.urls', namespace='web')),
    url(r'^api/', include('api.urls', namespace='api')),
]

web/urls.py
from django.conf.urls import url

from web.views.home import HomeView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
]

api/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


@receiver(post_save, sender=User)
def create_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class ModelBase(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Location(ModelBase):
    user = models.ForeignKey(User, related_name='locations')

    lat = models.DecimalField(max_digits=16, decimal_places=8)
    lng = models.DecimalField(max_digits=16, decimal_places=8)

    def __str__(self):
        return 'User {}: [{}, {}]'.format(self.user.pk, self.lat, self.lng)

api/views.py
from django.contrib.auth.models import User

from rest_framework.generics import ListCreateAPIView
from rest_framework.response import Response
from rest_framework.serializers import ModelSerializer, PrimaryKeyRelatedField, ReadOnlyField
from rest_framework.status import HTTP_201_CREATED, HTTP_400_BAD_REQUEST

from api.models import Location


class UserSerializer(ModelSerializer):
    locations = PrimaryKeyRelatedField(many=True, read_only=True)

    class Meta:
        model = User
        fields = ('id', 'email', 'username', 'password', 'locations')
        extra_kwargs = {'password': {'write_only': True}}

    def create(self, validated_data):
        user = User(
            email=validated_data.get('email', ''),
            username=validated_data['username']
        )
        user.set_password(validated_data['password'])
        user.save()
        return user


class UserListView(ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    def post(self, request, format='json'):
        serializer = UserSerializer(data=request.data)

        if serializer.is_valid():
            user = serializer.save()
            if user:
                token = user.auth_token
                json = serializer.data
                json['token'] = token.key if token else 'NA'
                return Response(json, status=HTTP_201_CREATED)

        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)


class LocationSerializer(ModelSerializer):
    user = ReadOnlyField(source='user.username')

    class Meta:
        model = Location
        fields = ('id', 'created', 'lat', 'lng', 'user')


class LocationListView(ListCreateAPIView):
    queryset = Location.objects.all()
    serializer_class = LocationSerializer

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

web/views/home.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'web/home.html'

web/templates/web/_includes/nav.html
<nav class="p1 clearfix bg-darken-1 caps">
  <div class="sm-col">
    <a href='{% url "web:index" %}' class="btn px1 py1">TODO</a>
  </div>
  <div class="sm-col-right">
    <a href='#!' class="btn px1 py1 h6 regular">...</a>
  </div>
</nav>

web/templates/web/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon.png">
    <title>Motley</title>
    {% block head %}{% endblock %}
    <link rel="stylesheet" href="https://unpkg.com/basscss@7.1.1/css/basscss.min.css">
  </head>
  <body>
    {% block content %}
      {% include "web/_includes/nav.html" %}
      <div class="p2 container">
        {% block container %}{% endblock %}
      </div>
    {% endblock %}
    {% block footerjs %}{% endblock %}
  </body>
</html>

web/templates/web/home.html
{% extends 'web/base.html' %}

{% block container %}
<h1 class='my3 center'>😎</h1>
{% endblock %}